# Generated by Django 6.0.4 on 2026-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsnapshot',
            name='model_type',
            field=models.CharField(choices=[('dummy', 'Dummy'), ('baseline', 'Baseline'), ('catboost', 'CatBoost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modelartifact',
            name='model_type',
            field=models.CharField(choices=[('dummy', 'Dummy'), ('baseline', 'Baseline'), ('catboost', 'CatBoost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reportartifact',
            name='report_type',
            field=models.CharField(choices=[('price_plot', 'Price plot'), ('target_distribution', 'Target distribution'), ('feature_importance', 'Feature importance'), ('metrics_plot', 'Metrics plot'), ('stability_table', 'Stability table'), ('stability_plot', 'Stability plot')], max_length=30),
        ),
    ]
