# Generated by Django 6.0.4 on 2026-05-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_alter_metricsnapshot_model_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportartifact',
            name='report_type',
            field=models.CharField(choices=[('price_plot', 'Price plot'), ('target_distribution', 'Target distribution'), ('feature_importance', 'Feature importance'), ('metrics_plot', 'Metrics plot'), ('stability_table', 'Stability table'), ('stability_plot', 'Stability plot'), ('forecast_replay', 'Forecast replay'), ('forecast_replay_table', 'Forecast replay table')], max_length=30),
        ),
    ]
